=== Nycene/NetBeansProjects/tp1_WebServ/src/tp1_webserv/TP1.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT etudiants (etudiant)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT etudiant (nom|prenom|age)*>
<!ATTLIST etudiant dep CDATA #IMPLIED>
<!ATTLIST etudiants annÃ©e CDATA #IMPLIED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nom (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT prenom (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT age (#PCDATA)>

=== Nycene/NetBeansProjects/tp1_WebServ/src/tp1_webserv/TP1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE etudiants SYSTEM "TP1.dtd">

<etudiants année="2 eme année"> 
    <etudiant dep="informatique" > 
        <nom> Singer </nom>
        <prenom> Nicolas</prenom>
</etudiant>
<etudiant dep="électrique">
        <nom> Trouilhet </nom>
        <prenom> Sylvie</prenom>
        <prenom> Sylva </prenom>
        <age> 22</age>
</etudiant>
</etudiants>
