=== Nycene/NetBeansProjects/tp2_WebServ/src/tp2_webserv/ouvrage.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ENTITY % element_commun "titre,auteur">
<!ENTITY % attribut_commun "langue CDATA #REQUIRED nbpage CDATA #IMPLIED">
<!ELEMENT ouvrage ((article|rapport)*)>
<!ELEMENT article (%element_commun;,section,(annee)?)>
<!ATTLIST article %attribut_commun;>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (nom,prenom,pays)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT section (para+)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT rapport (%element_commun;,chapitre)>
<!ATTLIST rapport %attribut_commun;>
<!ELEMENT chapitre (section+)>

=== Nycene/NetBeansProjects/tp2_WebServ/src/tp2_webserv/exercice1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ouvrage SYSTEM "ouvrage.dtd">
<ouvrage> 
    <article langue="arabe" nbpage="5">
        <titre> Evolution du monde</titre>
        <auteur> 
            <nom> Fatma</nom>
            <prenom> Tounsi</prenom>
            <pays> Tunisie </pays>
        </auteur>
        <section> 
            <para> tout a été dit </para>
        </section>
    </article>
    <rapport langue="français" nbpage="20">
        <titre> Xrapport</titre>
        <auteur> 
            <nom> Xnom </nom>
            <prenom> Xprenom</prenom>
            <pays> Xpays </pays>
        </auteur>
        <chapitre>
            <section> 
                <para> du texte</para>
            </section>
        </chapitre>
    </rapport>
    <article langue="français"> 
        <titre> Histoire du monde </titre>
        <auteur>
            <nom> Dupond</nom> 
            <prenom> Jean </prenom>
            <pays> France </pays>
        </auteur>
        <section> 
            <para> texte intègral>/</para>
        </section>
        <annee> 2000 </annee>
    </article>
</ouvrage>
